import Header from "@/Components/Header";
import Footer from "@/Components/footer";
import "./globals.css";
export const metadata = {
  title: "SRS Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        {children}
        <Footer/>
      </body>
    </html>
  );
}
